In [1]:
from nichenetpy.utils import (
    read_csv_cols,
)
from nichenetpy.parameter_optimization import construct_and_evaluate

import os
import requests
import pandas as pd
import session_info
import json
import numpy as np

In [2]:
network_path = os.path.normpath("./tutorial_files/model_construction/human")
if not os.path.exists(network_path):
    os.makedirs(network_path)
for filename in (
    "gr_human.csv",
    "lr_network_human.csv",
    "lr_sig_human.csv",
    "optimized_source_weights.csv",
    "annotation_data_sources.csv"
):
    file_path = os.path.join(network_path, filename)
    if not os.path.exists(file_path):
        res = requests.get(f"https://zenodo.org/records/14929618/files/{filename}")
        with open(file_path, "wb") as file:
            file.write(res.content)

In [3]:
gr_network = pd.DataFrame(read_csv_cols(os.path.join(network_path, "gr_human.csv")))
lr_network = pd.DataFrame(read_csv_cols(os.path.join(network_path, "lr_network_human.csv")))
sig_network = pd.DataFrame(read_csv_cols(os.path.join(network_path, "lr_sig_human.csv")))

In [4]:
train_path = "D:/Data/nichenetpy/model_optimization"
with open(os.path.join(train_path, "settings_training_f1234.json"), "rb") as file:
    settings_CV = json.loads(file.read())
settings = settings_CV["settings"]

In [5]:
gr_network = gr_network[
    ((gr_network["database"] == "NicheNet_LT") & np.array([fr not in settings_CV["forbidden_ligands_nichenet"] for fr in gr_network["from"]]))
    |
    ((gr_network["database"] == "CytoSig") & np.array([fr not in settings_CV["forbidden_ligands_cytosig"] for fr in gr_network["from"]]))
]

In [6]:
eval = construct_and_evaluate(
    lr_network,
    gr_network,
    sig_network,
    settings
)

c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pcc = pearsonr(response, prediction).statistic
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
c:\Users\victorm\Documents\nichenetpy\.hatch\Lib\site-packages\sklearn\metrics\_ranking.py:1183: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
C:\Users\victorm\Documents\nichenetpy\src\nichenetpy\metrics.py:161: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.

In [7]:
eval["performances_target_prediction"]

,setting,ligand,auroc,pearson,aupr,aupr_corrected
0,ifna_ifng_timeseries,IFNG,0.530994,0.021983,0.012009,0.004159
1,spectrum_Ifnb1,IFNB1,0.513481,0.020767,0.041388,0.009011
2,GSE6085_IL2_timeseries,IL2,0.501726,0.000986,0.026020,-0.000206
3,il20family_Il1b,IL1B,0.514967,0.030652,0.051478,0.026124
4,rat_Ifng,IFNG,0.526954,0.038939,0.044894,0.014359
...,...,...,...,...,...,...
126,dataset_WNT3A,WNT3A,0.488456,-0.006206,0.022021,-0.000875
127,dataset_INHBA,INHBA,0.463189,-0.021061,0.025520,-0.002172
128,dataset_IL36A,IL36A,0.491443,-0.004796,0.026194,0.000049
129,dataset_IL12A,IL12A,0.627616,0.147390,0.072237,0.046865
130,dataset_CD40,CD40,0.568104,0.058682,0.027000,0.012458

In [8]:
eval["performances_ligand_prediction"]

,metric,group,ligand,aupr,aupr_corrected,auroc,pearson
0,aupr,dataset_GDNF,GDNF,0.013889,-0.001984,0.435484,-0.081185
1,aupr_corrected,dataset_GDNF,GDNF,0.013889,-0.001984,0.435484,-0.081185
2,auroc,dataset_GDNF,GDNF,0.017857,0.001984,0.564516,0.066000
3,pearson,dataset_GDNF,GDNF,0.015625,-0.000248,0.500000,-0.011266
0,aupr,dataset_IL2,IL2,0.009804,-0.006069,0.193548,-0.097522
...,...,...,...,...,...,...,...
3,pearson,pdgf_Pdgf,PDGFB,0.025000,0.009127,0.693548,0.015944
0,aupr,GSE10315_BMP2_timeseries,BMP2,0.015625,-0.000248,0.500000,-0.064238
1,aupr_corrected,GSE10315_BMP2_timeseries,BMP2,0.015625,-0.000248,0.500000,-0.064238
2,auroc,GSE10315_BMP2_timeseries,BMP2,0.010417,-0.005456,0.241935,-0.100581
3,pearson,GSE10315_BMP2_timeseries,BMP2,0.010417,-0.005456,0.241935,-0.092194

In [9]:
eval["performances_ligand_prediction"]

,metric,group,ligand,aupr,aupr_corrected,auroc,pearson
0,aupr,dataset_GDNF,GDNF,0.013889,-0.001984,0.435484,-0.081185
1,aupr_corrected,dataset_GDNF,GDNF,0.013889,-0.001984,0.435484,-0.081185
2,auroc,dataset_GDNF,GDNF,0.017857,0.001984,0.564516,0.066000
3,pearson,dataset_GDNF,GDNF,0.015625,-0.000248,0.500000,-0.011266
0,aupr,dataset_IL2,IL2,0.009804,-0.006069,0.193548,-0.097522
...,...,...,...,...,...,...,...
3,pearson,pdgf_Pdgf,PDGFB,0.025000,0.009127,0.693548,0.015944
0,aupr,GSE10315_BMP2_timeseries,BMP2,0.015625,-0.000248,0.500000,-0.064238
1,aupr_corrected,GSE10315_BMP2_timeseries,BMP2,0.015625,-0.000248,0.500000,-0.064238
2,auroc,GSE10315_BMP2_timeseries,BMP2,0.010417,-0.005456,0.241935,-0.100581
3,pearson,GSE10315_BMP2_timeseries,BMP2,0.010417,-0.005456,0.241935,-0.092194

In [10]:
session_info.show()